switch:
  - platform: rpiswitch
    scan_interval: 10
    pin: 17
    name: "Room Light Switch"
    invert_logic: false

  - platform: rpiswitch
    scan_interval: 10
    pin: 18
    name: "Corridor Light Switch"
    invert_logic: false

  - platform: rpiswitch
    scan_interval: 10
    pin: 22
    name: "Kitchen Light Switch"
    invert_logic: false

sensor:
  - platform: ads1115_power
    scan_interval: 10
    channel: 3
    name: "Room Light Switch Power"
    voltage: 225
    samples: 100
    gain: 1
    pf: 0.6

  - platform: ads1115_power
    scan_interval: 10
    channel: 1
    name: "Corridor Light Switch Power"
    voltage: 225
    samples: 100
    gain: 1
    pf: 0.6

  - platform: ads1115_power
    scan_interval: 10
    channel: 0
    name: "Kitchen Light Switch Power"
    voltage: 225
    samples: 100
    gain: 1
    pf: 0.6